Adding ABAP - Cleaner to the Leitffaden #42 #45
1DSAG/ADT-Leitfaden pull request #47
Opened 2023-12-30 18:51 UTC by ABAP-Pete25

Information about ABAP Cleaner added to the Leitfaden in different sections.

Added to motivation - section Refactoring - as Teaser
Added to motivation - section Tools as teaser

Added to working with ADT - basic working instructions in section refactoring

Added to plugin chapter - some details about installing and features.

Additionally fixed broken link to Eclipse developer tools.

2023-12-31 11:11 UTC, stockbal approved these changes
Looks good to me

2024-01-02 11:48 UTC, ConjuringCoffee requested changes

2024-01-02 11:48 UTC, ConjuringCoffee commented on docs/plug-ins/open-source-adt-plugins.md
> +Das ABAP Cleaner Plug-in ist ein Tool das unbedingt eingesetzt werden sollte und bei allen ADT Installationen mitinstalliert werden.
```suggestion
Das ABAP Cleaner Plug-in ist ein Tool das unbedingt eingesetzt werden sollte und bei allen ADT Installationen mitinstalliert werden sollte.
```

2024-01-02 11:48 UTC, ConjuringCoffee commented on docs/plug-ins/open-source-adt-plugins.md
> +Das ABAP Cleaner Plug-in ist ein Tool das unbedingt eingesetzt werden sollte und bei allen ADT Installationen mitinstalliert werden.
Alternativ auch:

```suggestion
Das ABAP Cleaner Plug-in ist ein Tool das unbedingt eingesetzt und bei allen ADT Installationen mitinstalliert werden sollte.
```

2024-01-02 12:26 UTC, merged